# Generated by Django 3.0 on 2021-01-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='oontactdata',
            new_name='contactdata',
        ),
    ]
