# Generated by Django 3.0 on 2021-01-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0002_auto_20210113_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdata',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='contactdata',
            old_name='first_nmae',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='contactdata',
            old_name='last_name',
            new_name='lname',
        ),
    ]
